import type { Metadata } from "next";
import { I18nextProvider } from 'react-i18next';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/styles/globals.css';
import i18n from '@/lib/i18n';
import ReduxProvider from "@/redux/ReduxProvider";
import MainLayout from "@/components/layout/MainLayout";
import I18nextProviderWrapper from "@/lib/I18nextProviderWrapper";
import 'keen-slider/keen-slider.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rentify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <I18nextProviderWrapper>
            <MainLayout>{children}</MainLayout>
          </I18nextProviderWrapper>
        </ReduxProvider>
      </body>
    </html >
  );
}
